ingesterPort: 9044                            # Port to run the Ingestion Server on, Example: 9044

retentionPeriod: "6 months"                  # Retention Period for the LLM Data, Example: "24 hours", "7 days", "6 months"

# Comment out either 'localFile' or 'url' to use only one at a time.  
pricingInfo:
  # localFile:
  #   path: "/assets/pricing.json" # Path to local JSON file with LLM Pricing data
  url: "https://raw.githubusercontent.com/dokulabs/doku/main/assets/pricing.json" # URL to download Pricing data file

# Configuration for the Doku Backend Database (TimescaleDB)
dbConfig:
  name: "DBNAME"                              # Name of the database, Example: "postgres"
  username: "USERNAME"                        # Username to connect to the database, Example: "admin"
  password: "PASSWORD"                        # Password to connect to the database, Example: "DOKU"
  host: "HOSTURL"                             # Hostname of the database, Example: "174.21.1.2"
  port: DBPORT                                # Port of the database, Example: 5432
  sslMode: SSLMODE                            # SSL Mode of the database, Example: "require"
  maxOpenConns: MAXOPENCONNS                  # Maximum number of open connections to the database, Example: 15
  maxIdleConns: MAXOPENCONNS                  # Maximum number of idle connections to the database, Example: 15

# Configure Platform to export LLM Observability Data from Doku
# Only one platform can be enabled at a time, To enable a platform, set enabled to true and fill in the required fields for that platform.
connections:
  enabled: false                                                  # Enable or Disable the Observability Platform, Example: true
  # grafanaCloud:
  #   promUrl: "influx-line-proxy-url"                            # URL to the Influx Line Proxy URL of the Grafana Cloud Prometheus Instance
  #   promUsername: "prometheus-userid"                           # Prometheus User ID of the Grafana Cloud Prometheus Instance
  #   lokiUrl: "loki-push-url"                                    # URL to the Loki Push URL of the Grafana Cloud Loki Instance
  #   lokiUsername: "loki-username"                               # Loki Username of the Grafana Cloud Loki Instance
  #   accessToken: "grafana-cloud-access-token"                   # Access Token of the Grafana Cloud Instance

  # newRelic:
  #   metricsUrl: "https://metric-api.newrelic.com/metric/v1"     # URL to the New Relic Metric API
  #   logsUrl: "https://log-api.newrelic.com/log/v1"              # URL to the New Relic Log API
  #   key: "newrelic-api-key"                                     # Ingest API Key of the New Relic Account

  # datadog:
  #   metricsUrl: "https://api.datadoghq.com/api/v1/series"       # URL to the DataDog Metrics API
  #   logsUrl: "https://http.logs.datadoghq.com/api/v2/logs"      # URL to the DataDog Logs API
  #   apiKey: "datadog-api-key"                                   # API Key of the DataDog Account

  # signoz:
  #   url: "https://api.datadoghq.com/api/v1/series"              # URL to the DataDog Metrics API
  #   apiKey: "datadog-api-key"                                   # API Key of the DataDog Account

  # dynatrace:
  #   metricsUrl: "https://{your-env-id}.live.dynatrace.com/api/v2/metrics/ingest"            # URL to the Dynatrace Metrics API
  #    logsUrl: "https://{your-env-id}.live.dynatrace.com/api/v2/logs/ingest"                 # URL to the Dynatrace Logs API
  #    apiKey: <your-dynatrace-api-key>                                                       # API Key of the Dynatrace Account